[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer-runs = 10_000_000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC}"
base_sepolia = "${BASE_SEPOLIA_RPC}"
xdai = "${GNOSIS_CHAIN_RPC}"

[etherscan]
sepolia = { key = "${ETHERSCAN_MULTICHAIN_KEY}", url = "https://api.etherscan.io/v2/api?chainid=11155111" }
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
xdai = { key = "${ETHERSCAN_MULTICHAIN_KEY}", url = "https://api.etherscan.io/v2/api?chainid=100" }
